version: "2.23.0"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - data_sql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    ports:
      - $RABBITMQ_MANAGEMENT_PORT:$RABBITMQ_MANAGEMENT_PORT
      - $RABBITMQ_PORT:$RABBITMQ_PORT
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - data_rabbitmq:/var/lib/rabbitmq

  live_data_receiver-microservice:
    build: ./live-data-receiver-microservice/api
    container_name: live_data_receiver
    image: maven:3-openjdk-17
    volumes:
      - ./live-data-receiver-microservice:/live-data-receiver-microservice
    env_file:
      - .env
    ports:
      - $LIVE_DATA_RECEIVER_PORT:$LIVE_DATA_RECEIVER_PORT
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.rabbitmq.host":"rabbitmq",
        "spring.rabbitmq.port":"$RABBITMQ_PORT",
        "spring.rabbitmq.username":"$RABBITMQ_USER",
        "spring.rabbitmq.password":"$RABBITMQ_PASSWORD",
        "api.key":"$API_KEY"
        }'
    working_dir: /live-data-receiver-microservice/api
    command: sh -c "./mvnw spring-boot:run"

  flight-microservice:
    build: ./flight-microservice/api
    container_name: flight
    image: maven:3-openjdk-17
    volumes:
      - ./flight-microservice:/flight-microservice
    env_file:
      - .env
    ports:
      - $FLIGHT_PORT:$FLIGHT_PORT
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysql:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE",
        "spring.datasource.username":"$MYSQL_USER",
        "spring.datasource.password":"$MYSQL_PASSWORD",
        "spring.redis.host":"redis",
        "spring.redis.port":"6379",
        "spring.rabbitmq.host":"rabbitmq",
        "spring.rabbitmq.port":"$RABBITMQ_PORT",
        "spring.rabbitmq.username":"$RABBITMQ_USER",
        "spring.rabbitmq.password":"$RABBITMQ_PASSWORD"
        }'
    working_dir: /flight-microservice/api
    command: sh -c "./mvnw spring-boot:run"

  payment-microservice:
    build: ./payment-microservice/api
    container_name: payment
    image: maven:3-openjdk-17
    volumes:
      - ./payment-microservice:/payment-microservice
    env_file:
      - .env
    ports:
      - $PAYMENT_PORT:$PAYMENT_PORT
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysql:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE",
        "spring.datasource.username":"$MYSQL_USER",
        "spring.datasource.password":"$MYSQL_PASSWORD"
        }'
    working_dir: /payment-microservice/api
    command: sh -c "./mvnw spring-boot:run"

  user-microservice:
    build: ./user-microservice/api
    container_name: user
    image: maven:3-openjdk-17
    volumes:
      - ./user-microservice:/user-microservice
    env_file:
      - .env
    ports:
      - $USER_PORT:$USER_PORT
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysql:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE",
        "spring.datasource.username":"$MYSQL_USER",
        "spring.datasource.password":"$MYSQL_PASSWORD"
        }'
    working_dir: /user-microservice/api
    command: sh -c "./mvnw spring-boot:run"

  frontend:
    build:
      context: web-ui/frontend
    container_name: frontend
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    volumes:
      - node_modules:/web-ui/frontend/node_modules
      - ./web-ui/frontend:/web-ui/frontend
    stdin_open: true
    tty: true
    env_file: .env

  display:
    build:
      context: airport-display/frontend
    container_name: display
    ports:
      - $DISPLAY_PORT:$DISPLAY_PORT
    volumes:
      - airport-display-node-modules:/airport-display/frontend/node_modules
      - ./airport-display/frontend:/airport-display/frontend
    stdin_open: true
    tty: true
    env_file: .env

  nginx-proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - display
      - flight-microservice
      - payment-microservice
      - user-microservice
    env_file: .env

volumes:
  airport-display-node-modules:
    driver: local
  node_modules:
    driver: local
  data_sql:
    driver: local
  data_rabbitmq:
    driver: local
